### ISSUE TITLE
Style join page

### ISSUE THREAD

**Issue by Voovs** [Acumen-syndicate-Ltd/SimpleChatSystem#3]
The join page is found at src/views.Join.vue. Here is a [live version](https://dorpn.com/join).

It's written entirely in Vue CLI, yet we only need the CSS changed, which doesn't require you to know the framework.

The current style of Join.vue is confusing for users. Please style so that it creates a clear experience for our users while navigating the rooms.

**Comment by bonniewhy** [comment]
Has anyone said something specifically about what's confusing?
